project:
  type: book

book:
  title: "What They Forgot to Teach You About R"
  subtitle: "The stuff you need to know about R, besides statistical analysis."
  repo-url: https://github.com/rstats-wtf/what-they-forgot
  site-url: https://rstats.wtf
  google-analytics: UA-131757508-1
  author:
    - Jennifer Bryan
    - Jim Hester
    - Shannon Pileggi
    - E. David Aja
  chapters:
    - index.qmd
    - part: "A holistic workflow"
      chapters:
        - 11-source-and-blank-slates.qmd
        - 12-projects.qmd
        - 13-practice-safe-paths.qmd
        - 14-naming-files.qmd
        - 15-api-for-an-analysis.qmd
    - part: "Personal R Administration"
      chapters:
        - get-to-know-your-r-installation.qmd
        - r-startup.qmd
        - maintaining-r.qmd
        - install-single-package.qmd
    - part: "All is Fail"
      chapters:
        - debugging-r.qmd
        - read-source.qmd
        - reprexing.qmd
    - sessioninfo.qmd

bibliography: [book.bib, packages.bib]
link-citations: true

format:
  html:
    theme: cosmo
