project:
  type: book

book:
  title: "What They Forgot to Teach You About R"
  subtitle: "The stuff you need to know about R, besides data analysis."
  repo-url: https://github.com/rstats-wtf/what-they-forgot
  site-url: https://rstats.wtf
  google-analytics: UA-131757508-1
  author:
    - Jennifer Bryan
    - Jim Hester
    - Shannon Pileggi
    - E. David Aja
  chapters:
    - index.qmd
    - part: "A holistic workflow"
      chapters:
        - source-and-blank-slates.qmd
        - projects.qmd
        - practice-safe-paths.qmd
        - naming-files.qmd
        - api-for-an-analysis.qmd

    - part: personal-radmin.qmd
      chapters:
        - r-startup.qmd
        - installing-packages.qmd
        - reproducible-environments.qmd
        - installing-r.qmd
        - maintaining-r.qmd

    - part: "All is Fail"
      chapters:
        - debugging-r.qmd
        - read-source.qmd
        - reprexing.qmd
    - sessioninfo.qmd

bibliography: [book.bib, packages.bib]
link-citations: true

format:
  html:
    theme: cosmo
